Apply enum validator
catchfashion/url-catalog-generator pull request #2
Opened 2021-03-08 06:22 UTC by HoseungJang

[Asana](https://app.asana.com/0/1128532709616896/1200028492394648)

enum 검사하는 코드를 추가합니다.

2021-03-08 06:23 UTC, HoseungJang commented
이거 머지하고 배포 어떻게 하면 되나요?
build -> npm publish?

2021-03-08 08:08 UTC, breath103 requested changes

2021-03-08 08:08 UTC, breath103 commented on src/url_schema.ts
> +                if (pathComponent.schema?.enum) {
if () 가 throw를 위한 추가 구문인데 L116 / L121을 중복으로 쓸 이유가 없지 않나 애초에?

```
if (xx) {
   throw ()
}
(output as any)[pathComponent.name] = decoded;
```

2021-03-08 08:08 UTC, HoseungJang commented on src/url_schema.ts
> +                if (pathComponent.schema?.enum) {
앗 그러네요

2021-03-08 08:15 UTC, breath103 requested changes

2021-03-08 08:15 UTC, breath103 commented on src/url_schema.ts
> +                if (pathComponent.schema?.enum && pathComponent.schema.enum.find((value) => value === decoded)) {
?아니 ! pathComponent.schema.enum.find((value) => value === decoded) 이겠죠;

2021-03-08 08:16 UTC, breath103 commented on src/url_schema.ts
> +                if (pathComponent.schema?.enum && pathComponent.schema.enum.find((value) => value === decoded)) {
이거 https://github.com/catchfashion/url-catalog-generator/blob/master/src/__test__/url_schema_spec.ts 테스트 추가해주세요.

2021-03-08 10:40 UTC, breath103 approved these changes

2021-03-08 10:40 UTC, merged

2021-03-08 20:30 UTC, mooyoul commented on src/url_schema.ts
> +                if (pathComponent.schema?.enum && !pathComponent.schema.enum.find((value) => value === decoded)) {
primitive type 비교면 그냥 .includes(decoded) 썼어도 되었겠네요

2021-03-09 08:05 UTC, hoseungme commented on src/url_schema.ts
> +                if (pathComponent.schema?.enum && !pathComponent.schema.enum.find((value) => value === decoded)) {
some을 쓸 수도 있고.. 선택지는 많긴 하네요
의미상 includes가 가장 가까운 선택지인거 같긴 하지만..